const express = require('express');
const cors = require('cors');
const { exec } = require('child_process');
const { promisify } = require('util');
const fs = require('fs').promises;
const path = require('path');
const os = require('os');

const execAsync = promisify(exec);
const app = express();

app.use(cors());
app.use(express.json({ limit: '10mb' }));

app.get('/health', (req, res) => {
  res.json({ status: 'ok', service: 'lilypond-converter' });
});

app.post('/convert', async (req, res) => {
  let tempDir = null;

  try {
    const { content } = req.body;

    if (!content) {
      return res.status(400).json({ error: 'Missing LilyPond content' });
    }

    // Create a temporary directory
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'lilypond-'));
    const inputFile = path.join(tempDir, 'input.ly');
    const outputBasename = 'output';

    // Write the LilyPond content to a temporary file
    await fs.writeFile(inputFile, content, 'utf-8');

    // Run LilyPond to convert to SVG
    try {
      await execAsync(`lilypond -dbackend=svg -o "${path.join(tempDir, outputBasename)}" "${inputFile}"`, {
        cwd: tempDir,
        timeout: 30000,
      });
    } catch (error) {
      console.error('LilyPond conversion error:', error);
      return res.status(500).json({
        error: 'Failed to convert LilyPond to SVG',
        details: error.message || 'Unknown error'
      });
    }

    // Read the generated SVG file(s)
    const files = await fs.readdir(tempDir);
    const svgFiles = files.filter(f => f.endsWith('.svg')).sort();

    if (svgFiles.length === 0) {
      return res.status(500).json({
        error: 'No SVG output generated by LilyPond',
        details: 'LilyPond conversion completed but no SVG files were created'
      });
    }

    // Read all SVG files
    const svgContents = await Promise.all(
      svgFiles.map(file => fs.readFile(path.join(tempDir, file), 'utf-8'))
    );

    res.json({
      success: true,
      svgs: svgContents,
      pageCount: svgContents.length
    });

  } catch (error) {
    console.error('Error converting LilyPond to SVG:', error);
    res.status(500).json({
      error: 'Failed to convert LilyPond to SVG',
      details: error.message || 'Unknown error'
    });
  } finally {
    // Clean up temporary directory
    if (tempDir) {
      try {
        await fs.rm(tempDir, { recursive: true, force: true });
      } catch (error) {
        console.error('Error cleaning up temp directory:', error);
      }
    }
  }
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, '0.0.0.0', () => {
  console.log(`LilyPond converter running on port ${PORT}`);
});
